import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { AddressTag } from '@/components/common/AddressTag';
import { CoinAmount } from '@/components/common/CoinAmount';
import { CountdownTimer } from '@/components/common/CountdownTimer';
import { StatusBadge } from '@/components/common/StatusBadge';
export function WantedPoster({ bounty }) {
    return (_jsxs("article", { className: "panel group flex h-full flex-col p-5 transition hover:-translate-y-1 hover:border-frost/30", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Priority Contract" }), _jsxs("div", { className: "mt-3 flex flex-wrap items-center gap-2", children: [_jsx(AddressTag, { address: bounty.target }), _jsx(StatusBadge, { status: bounty.status })] })] }), _jsxs("div", { className: "rounded-2xl border border-amber/25 bg-amber/10 px-4 py-3 text-right", children: [_jsx("p", { className: "label-muted", children: "Reward" }), _jsx("p", { className: "mt-1 text-lg font-semibold text-amber", children: _jsx(CoinAmount, { amount: bounty.rewardAmount }) })] })] }), _jsx("p", { className: "mt-4 min-h-[72px] text-sm leading-6 text-muted", children: bounty.description ?? 'No mission brief attached. Operators should inspect the target contract directly.' }), _jsxs("div", { className: "mt-4 grid gap-3 text-sm text-muted sm:grid-cols-2", children: [_jsxs("div", { className: "rounded-2xl border border-line/60 bg-steel/45 p-3", children: [_jsx("p", { className: "label-muted", children: "Creator" }), _jsx("div", { className: "mt-2", children: _jsx(AddressTag, { address: bounty.creator }) })] }), _jsxs("div", { className: "rounded-2xl border border-line/60 bg-steel/45 p-3", children: [_jsx("p", { className: "label-muted", children: "Expiry Window" }), _jsx("p", { className: "mt-2 font-semibold text-ink", children: _jsx(CountdownTimer, { expiresAt: bounty.expiresAt }) })] })] }), _jsxs("div", { className: "mt-5 flex items-center justify-between pt-1", children: [_jsxs("span", { className: "text-xs uppercase tracking-[0.22em] text-muted", children: ["Object ", bounty.id.slice(0, 10), "..."] }), _jsx(Link, { to: `/bounties/${bounty.id}`, className: "button-secondary text-xs", children: "Inspect Contract" })] })] }));
}
